target 'iosApp' do
  use_frameworks!
  platform :ios, '17.0'
  pod 'composeApp', :path => '../composeApp'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseAuth'
  pod 'FirebaseCrashlytics'
end
